### ISSUE TITLE
Consolidate Pantheon deploy workflows

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/create-wordpress-project#35]
# User Story

> As a maintainer, I want to have one deploy action rather than two so that I can reduce code duplication in our actions.

# Acceptance Criteria

- Create new GitHub repo called `action-deploy-to-pantheon` that will function similarly to [action-deploy-to-remote-repository](https://github.com/alleyinteractive/action-deploy-to-remote-repository) - and will use that action in its steps.
- Add config vars to the action for everything that is conceivably different between projects, such as secrets, PHP version, node version, etc.
- Combine logic from multidev and production to use the same action but fork if deploying to prod
- Update this repo to use the new abstracted action and provide config vars to rely on it to do the build and deploy.

# Context

The Pantheon deploy workflows are nearly identical. The only difference is that deploys to a `production` branch result in a deployment to the `dev` environment on Pantheon and then trigger deploys to `test` and `live`. Ideally, we could use one workflow for this with conditions for merges to `production` that handle the alternate workflow and DRY up the config quite a bit.

**Comment by benpbolton** [comment]
@kevinfodness can you suggest a project or team lead that might be interested in testing this as I work through it?

**Comment by benpbolton** [comment]
There is currently a pre-release (published) github version [here](https://github.com/alleyinteractive/action-deploy-to-pantheon/releases/tag/v0.0.2) that likely needs edits/updates with real-world testing. 

It should be testable like:

```

    # Build your project here
    # ...

    - name: Deploy to Pantheon
      uses: alleyinteractive/action-deploy-to-pantheon@v0.0.2
      with:
        pantheon_site: 'your-site-name'
        pantheon_site_id: '12345678-YOUR-SITE-ID00-123456789123'
        pantheon_machine_token: ${{ secrets.SSH_KEY }}
        ssh-key: ${{ secrets.SSH_KEY }}
        destination_directory: 'wp-content/'
        autopromote: 'true'
        pantheon_env_name: ${{ github.ref_name }}
```

*edit: corrected `ssh_key` reference to `ssh-key`
